# This is a basic workflow to help you get started with Actions

name: Deploy Lambda Function - v1

# Controls when the workflow will run
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Zip Lambda - v1 code
        run: |
          aws lambda create-function \
            --function-name python-lambda1 \
            --runtime python3.9 \
            --zip-file fileb://base.zip \
            --handler lambda_function.handler \
            --role arn:aws:iam::123456789012:role/lambda-execution-rolearn:aws:iam::332093714913:role/lambda-canary-execution-role
          
      # - name: Zip Lambda - v1 code
      #   run: |
      #     aws lambda update-function-code \
      #       --function-name python-lambda \
      #       --zip-file fileb://version1.zip
